# Generated by Django 4.2.14 on 2024-10-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('idade', models.CharField(max_length=30)),
                ('comentarios', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
