# Generated by Django 5.1.1 on 2024-10-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastros',
            name='idade',
            field=models.CharField(max_length=3),
        ),
    ]
