# Generated by Django 5.1.1 on 2024-10-07 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_cadastros_bairro_cadastros_celular_cadastros_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastros',
            name='comentarios',
        ),
    ]
