# Generated by Django 5.1.1 on 2024-10-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_alter_cadastros_idade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastros',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='cadastros',
            name='idade',
        ),
        migrations.AddField(
            model_name='cadastros',
            name='bairro',
            field=models.CharField(default='Bairro não informado', max_length=100),
        ),
        migrations.AddField(
            model_name='cadastros',
            name='cidade',
            field=models.CharField(default='Cidade não informada', max_length=30),
        ),
        migrations.AddField(
            model_name='cadastros',
            name='complemento',
            field=models.CharField(default='Complemento não informado', max_length=50),
        ),
        migrations.AddField(
            model_name='cadastros',
            name='rua',
            field=models.CharField(default='Rua não informada', max_length=150),
        ),
        migrations.AlterField(
            model_name='cadastros',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
