# Generated by Django 5.1.1 on 2024-10-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_remove_cadastros_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastros',
            name='cep',
            field=models.CharField(default='', max_length=9),
        ),
    ]
