# Generated by Django 5.1.1 on 2024-10-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0004_alter_cadastros_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastros',
            name='cpf',
            field=models.CharField(default='', max_length=14),
        ),
    ]
