# Generated by Django 5.1.1 on 2024-10-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0004_cadastros_celular_cadastros_cep_cadastros_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastros',
            name='celular',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cadastros',
            name='cep',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cadastros',
            name='cpf',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cadastros',
            name='idade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cadastros',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
