# Generated by Django 5.1.1 on 2024-10-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0005_alter_cadastros_celular_alter_cadastros_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastros',
            name='celular',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='cadastros',
            name='cep',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='cadastros',
            name='cpf',
            field=models.CharField(default='', max_length=11),
        ),
    ]
